### ISSUE TITLE
Creating minimal plugin reference for 3rd party plugin

### ISSUE THREAD

**Issue by ColeTMNZ** [versionpress/support#131]
I'm Attempting to to provide a minimilast definition for a plugin that i'm using. The plugin in question comes as supporting functionality for a paid theme.

The plugin is **movedo_extension** - this provides many many many things.

I'm using some specific things at the moment, a couple of short codes. (if its relevant, the shortcodes are constructed through integration with WPBakery's Page Builder) 

So far - I have tried to 'map' 2 shortcodes as per the 3rd party plugin documentation:

wp-content/.versionpress/plugins/movedo-extension/shortcodes.yml
```
shortcode-locations:
  post:
    - post_content

shortcodes:
  movedo_icon_box:
    icon_image: attachment
    retina_icon_image: attachment
  movedo_media_box:
    image: attachment
```
The shortcodes i currently care about are _movedo_icon_box_ and _movedo_media_box_ - the shortcodes have attributes referencing post attachments - attributes named _icon_image_ and _retina_icon_image_

**System Info**
- VersionPress version: 4.0-beta (Github Release)
- WordPress version: 4.9.0
- OS, webserver, PHP: Redhat/nginx/php 7
- Git version: 1.8.1 and 2.7.4 (Different system)
