### ISSUE TITLE
Hook vp_before_synchronization_{$entityName} not working

### ISSUE THREAD

**Issue by beabri** [versionpress/support#152]
Hi all,

I want to make an `ALTER TABLE` on a Yoast Seo Meta table before Versionpress DB synchronization, so I created a file `hook.php` inside versionpress folder `wp-content\.versionpress\plugins\wordpress_seo`, but it seems not to execute code when the action is called. 
I'm using `vp_before_synchronization_{$entityName}`action.

This is the `hook.php` code:

```
error_log('hello world');

<?php

add_action('vp_before_synchronization_yoast_seo_meta', function () {
    error_log('execute before yoast_seo_meta synchro');
});

?>

```
When I execute the`restore_site` command, I read `Hello world`, but anything else.
Am I missing something?

Thanks a lot.

- VersionPress version: 4.0-beta-16-g2071052a
- WordPress version: 4.9.8
- PHP: 5.6.30
- Git version: 2.12.2

**Comment by pavelevap** [comment]
Hi @beabri,

sorry for delay :-(
It looks like you find a bug, because related core actions does not seem to work for me too, for example [this](https://github.com/versionpress/versionpress/blob/f25e6f07b14828523e3a5f2b0c3107abc43e638c/plugins/versionpress/.versionpress/hooks.php#L574). Does it work when you try to hook (and log) to standard `post` entity, for example `vp_before_synchronization_post`?

`yoast_seo_meta` and `yoast_seo_link` are custom entities for Yoast SEO plugin, could you share your addon for VP (schema) for this plugin to help us test it?

**Comment by beabri** [comment]
Hi @pavelevap, don't worry.

I tried with `vp_before_synchronization_post` but it doesn't seem to hook neither log anything.

This is the schema:

```
yoast_seo_link:
  table: yoast_seo_links
  id: id
  references:
    post_id: post
    target_post_id: post

yoast_seo_meta:
  table: yoast_seo_meta
  id: id
  references:
    object_id: post
  ignored-columns:
    - internal_link_count
    - incoming_link_count

option:
  ignored-entities:
    - 'option_name: wpseo_tracking_last_request'
    - 'option_name: wpseo_sitemap_*_cache_validator'
    - 'option_name: wpseo_sitemap_cache_validator_global'
    - 'option_name: recently_activated'

usermeta:
  ignored-entities:
    - 'meta_key: wp_yoast_notifications'
    - 'meta_key: community-events-location'
```

Let me you know if you need anything else.
